test_build_lipid_sphere(
    joinpath(test_dir(:data),"lipid","popc.pdb"),
    joinpath(test_dir(:tmp),"sphere_90A.pdb"),
    MolecularPDB.VMD,
    FibonacciSphere,
    90.,
    800,
    "sphere";
    inverted=false
    )
