test_build_lipid_sphere(
    joinpath(test_dir(:data),"lipid","popc.pdb"),
    joinpath(test_dir(:tmp),"sphere_1.pdb"),
    MolecularPDB.VMD,
    FibonacciSphere,
    100.,
    800,
    "sphere";
    inverted=false
    )
